name: CI
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt
    - name: Lint (flake8)
      run: flake8
    - name: Format check (black)
      run: black . --check
    - name: Tests
      run: pytest --cov=. --cov-report=term-missing --cov-report=xml
    - name: Complexity (radon)
      run: |
        radon cc -s -a . | tee radon-cc.txt
        radon raw . | tee radon-raw.txt
    - name: Lint count (flake8)
      run: flake8 --count || true
    - name: Upload coverage and metrics artifacts
      uses: actions/upload-artifact@v4
      with:
        name: metrics
        path: |
          coverage.xml
          radon-cc.txt
          radon-raw.txt
