name: Render UML Diagrams
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Render diagrams to PNG via Kroki
        run: |
          chmod +x scripts/render_diagrams_kroki.sh || true
          ./scripts/render_diagrams_kroki.sh
      - name: Commit rendered PNGs
        uses: EndBug/add-and-commit@v9
        with:
          add: 'docs/diagrams/*.png'
          message: 'chore(diagrams): render UML PNGs from Mermaid sources'
          default_author: github_actions
